# Site settings
title: THE ZIGGER ZONE
description: "A cosmic anomaly where Zigger’s weight defies spacetime—0.13 lbs heavier each day!"
url: "https://username.github.io" # Replace with your GitHub Pages URL
baseurl: "" # Adjust if needed (e.g., "/zigger-zone")

# Author info
author: 
  name: "Ziggertron 3000" # A quirky alias
  email: "zigger@intergalactic.zone" # Futuristic flair

# Build settings
theme: jekyll-theme-midnight # Dark, futuristic theme (or try "jekyll-theme-hacker")
markdown: kramdown
permalink: /:title # Quirky, simple URLs

# Plugins for extra zing
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables (used in templates)
zigger_start_date: "2025-02-20" # Starting date for Zigger’s weight
zigger_start_weight: 0 # Starting weight in pounds

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
